# Generated by Django 5.2.4 on 2025-07-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='idea_images/')),
                ('content', models.TextField()),
                ('interest', models.IntegerField(default=0)),
                ('devtool', models.CharField(choices=[('VSCode', 'VSCode'), ('PyCharm', 'PyCharm'), ('IntelliJ', 'IntelliJ'), ('Eclipse', 'Eclipse'), ('Other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
