# Generated by Django 5.2.4 on 2025-07-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y%m%d/', verbose_name='이미지')),
                ('content', models.TextField(verbose_name='내용')),
                ('interest', models.PositiveIntegerField(default=0, verbose_name='관심도')),
                ('devtool', models.CharField(choices=[('django', 'Django'), ('react', 'React'), ('vue', 'Vue'), ('spring', 'Spring')], max_length=20, verbose_name='개발툴')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
        ),
    ]
