# Generated by Django 5.2.4 on 2025-07-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('release', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=32)),
                ('score', models.CharField(max_length=32)),
                ('runtime', models.CharField(max_length=32)),
                ('director', models.CharField(max_length=32)),
                ('actor', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
